apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coraza-spoa.fullname" . }}
  labels:
    {{- include "coraza-spoa.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
  pre_rules.conf: |
    {{- .Values.rules.pre | nindent 4 }}
  post_rules.conf: |
    {{- .Values.rules.post | nindent 4 }}
