apiVersion: v1
kind: Service
metadata:
  name: {{ include "coraza-spoa.fullname" . }}
  labels:
    {{- include "coraza-spoa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ regexSplit ":" .Values.config.bind -1 | last }}
      protocol: TCP
      name: spoa
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "coraza-spoa.selectorLabels" . | nindent 4 }}
