apiVersion: v2
name: coraza-spoa
description: A Helm chart for Kubernetes to deploy Coraza SPOA WAF
home: https://github.com/corazawaf/coraza-spoa
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - waf
  - coraza
  - spoa
  - haproxy
